package DeviceErrorsAlarmEngine

import com.apigee.alarm.*;
import java.util.*;

global org.apache.commons.logging.Log log;

global AlarmService alarmService;

global Long appId;

dialect "java"

declare ClientLog
    @role( event )
    @timestamp(timeStamp)
    @expires( 30m )
end


declare AppErrorsAppIds
	type: Long
end

rule "AppErrorsAppIdsRule"
	no-loop true
when 
	$log : DeviceLogEntry( $appId : appId ) from entry-point "clientLogStream"
	not (exists AppErrorsAppIds(type == $appId))
then
	//For some reason, insertLogical does not work - NOTE: Fixed in Drools 5.2 <- Need to fix
	insert( new AppErrorsAppIds($appId));
end


rule "SimpleAlarm"
   salience -600
   no-loop true
when
 AppErrorsAppIds($appId : type);
 $assertLogs : ArrayList(size > 0) from collect (DeviceLogEntry(logLevel == DeviceLogEntry.ASSERT, appId == $appId) from entry-point "clientLogStream")                    
then

 log.info("Detected critical errors for " + $appId);
 alarmService.sendCriticalErrors($assertLogs, $appId);
end






